name: TEST Build and Deploy Docker Image

on:
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    name: 'Build and Deploy Docker Image'
    runs-on: ubuntu-latest
    steps:
      - name: "Build:checkout"
        uses: actions/checkout@v2
      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "adagrad"
          password: ${{ secrets.PAT }}
          repository: adagrad/findb_dolthub
          tags: latest