name: "Test the workflow still works after publishing a new image"

on:
  workflow_dispatch:
  registry_package:
    types: [ published, updated ]

jobs:
  development_job:
    runs-on: ubuntu-latest
    name: Test workflow
    steps:
      - name: list commands
        id: test
        uses: adagrad/findb_dolthub@v1
        env:
          REPO: adagrad
          DATABASE: findb
          DOLTHUB_SECRET_JWT: ${{ secrets.DOLTHUB_SECRET_JWT }}
          DOLTHUB_SECRET: ${{ secrets.DOLTHUB_SECRET }}
          DOLT_COMMIT_ARGS: "-m pipeline_test --allow-empty"
        with:
          command1: yfinance
          command2: symbol
          command_args: "--help"
      # TODO add reusable pull merge push step here
      - name: clone merge push
        uses: adagrad/findb_dolthub@v1
        env:
          REPO: adagrad
          DATABASE: findb
          DOLTHUB_SECRET_JWT: ${{ secrets.DOLTHUB_SECRET_JWT }}
          DOLTHUB_SECRET: ${{ secrets.DOLTHUB_SECRET }}
          DOLT_COMMIT_ARGS: "-m pipeline_merge_test --allow-empty"
        with:
          entrypoint: "/entrypoint_merge.sh ${{ steps.test.outputs.branch }}"
