name: "Test the workflow still works after publishing a new image"

on:
  workflow_dispatch:
  registry_package:
    types: [ published, updated ]

jobs:
  development_job:
    runs-on: ubuntu-latest
    name: Test workflow
    outputs:
      branch: ${{ steps.test.outputs.branch }}
    steps:
      - name: list commands
        id: test
        uses: adagrad/findb_dolthub@main
        env:
          REPO: adagrad
          DATABASE: findb
          DOLTHUB_SECRET_JWT: ${{ secrets.DOLTHUB_SECRET_JWT }}
          DOLTHUB_SECRET: ${{ secrets.DOLTHUB_SECRET }}
          DOLT_COMMIT_ARGS: "-m pipeline_test --allow-empty"
        with:
          command1: yfinance
          command2: symbol
          command_args: "--help"
  simulate_pr_merge:
    uses: adagrad/findb_dolthub/.github/workflows/local_merge.yml@main
    needs: development_job
    with:
      branch: ${{ needs.development_job.outputs.branch }}
