name: "TEST Upload Release Asset"

on:
  workflow_dispatch:


jobs:
  upload_asset:
    runs-on: ubuntu-latest
    name: Test uploading a release asset
    steps:

      - name: simulate database
        run: |
          echo "das ist ein test" > mock.fin.db.sqlite.lrz

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: mock.fin.db.sqlite.lrz
          asset_name: mock.fin.db.sqlite.lrz
          tag: latest
          overwrite: true
          body: "Updated fin.db.sqlite.lrz"

  download_asset:
    needs: upload_asset
    runs-on: ubuntu-latest
    name: Test downloading a release asset
    steps:

      - name: Download binaries from release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: adagrad/findb_dolthub
          version: tags/integration_test
          file: mock.fin.db.sqlite.lrz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: show simulated database
        run: |
          ls -l
          test -f mock.fin.db.sqlite.lrz
