name: Just Some Action Used for Testing

on:
  workflow_dispatch:
  registry_package:
    types: [ published, updated ]

env:
  REPO: adagrad
  DATABASE: integration_test
  DOLTHUB_SECRET_JWT: ${{ secrets.DOLTHUB_SECRET_JWT }}
  DOLTHUB_SECRET: ${{ secrets.DOLTHUB_SECRET }}
  DOLT_BRANCH: "foo/bar-${{ github.run_id }}-${{ github.run_attempt }}"
  TEST_TABLE: "test"

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test workflow
    steps:
      - name: count entries of table test
        id: count
        uses: adagrad/findb_dolthub@test
        with:
          args: "dolt sqlserver -d ${{ env.REPO }}/${{ env.DATABASE }} -b main --force-clone -f ${{ env.DOLT_BRANCH }} --push --and-exec \"mysql -h 127.0.0.1 -u root -D findb -e \\\"update ${{ env.TEST_TABLE }} set col1='${{ env.DOLT_BRANCH }}' where pk=0;\\\"\""

      - name: dolt database status
        id: status
        uses: adagrad/findb_dolthub@test
        with:
          args: "dolt status"

  simulate_pr_merge:
    needs: test_job
    runs-on: ubuntu-latest
    name: Merge branch into main
    steps:
      - name: merge into main
        uses: adagrad/findb_dolthub@test
        with:
          args: "dolt merge -d ${{ env.REPO }}/${{ env.DATABASE }} -s ${{ inputs.branch }} -t main -m '${{ inputs.commit_message }}' --theirs -p --delete-source"
