name: "TEST Find New Symbols"

on:
  workflow_dispatch:

env:
  RUNTIME: 2

jobs:
  search_symbols:
    runs-on: ubuntu-latest
    name: A job to look for new symbols
    steps:

      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: Download database from release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: adagrad/findb_dolthub
          version: tags/integration_test
          file: fin.db.sqlite.lrz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          lrzip -f -d fin.db.sqlite.lrz -o fin.db.sqlite

      - name: lookup new symbols
        uses: adagrad/findb_dolthub@integration_test
        with:
          args: "yfinance symbol --time ${{ env.RUNTIME }}"
          # resume last session
          # args: "yfinance symbol --time ${{ env.RUNTIME }}" -s yfsymbols.csv.existing.symbols -r yfsymbols.csv.possible.symbols

      - name: Archive database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          lrzip --lzo -f -o fin.db.sqlite.lrz fin.db.sqlite

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fin.db.sqlite.lrz
          asset_name: fin.db.sqlite.lrz
          tag: integration_test
          overwrite: true
          body: "Updated fin.db.sqlite.lrz"

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          context: .
          push: true
          registry: ghcr.io
          username: "adagrad"
          password: ${{ secrets.GHCR }}
          repository: adagrad/finget
          tags: integration_test

  update_info:
    needs: search_symbols
    runs-on: ubuntu-latest
    name: A job to look for detailed infos for new symbols
    steps:

      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: Download database from release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: adagrad/findb_dolthub
          version: tags/integration_test
          file: fin.db.sqlite.lrz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          lrzip -f -d fin.db.sqlite.lrz -o fin.db.sqlite

      - name: lookup info details
        uses: adagrad/findb_dolthub@integration_test
        with:
          args: "yfinance info --time ${{ env.RUNTIME }}"

      - name: Archive database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          lrzip --lzo -f -o fin.db.sqlite.lrz fin.db.sqlite

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fin.db.sqlite.lrz
          asset_name: fin.db.sqlite.lrz
          tag: integration_test
          overwrite: true
          body: "Updated fin.db.sqlite.lrz"

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "adagrad"
          password: ${{ secrets.GHCR }}
          repository: adagrad/finget
          tags: integration_test

  update_quote:
    needs: update_info
    runs-on: ubuntu-latest
    name: A job to update missing quotes
    steps:

      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: Download database from release
        uses: dsaltares/fetch-gh-release-asset@master
        with:
          repo: adagrad/findb_dolthub
          version: tags/integration_test
          file: fin.db.sqlite.lrz
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          lrzip -f -d fin.db.sqlite.lrz -o fin.db.sqlite

      - name: fetch new quotes
        uses: adagrad/findb_dolthub@integration_test
        with:
          args: "yfinance quote -i 0 --include-new --time ${{ env.RUNTIME }} --clean"

      - name: Archive database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          lrzip --lzo -f -o fin.db.sqlite.lrz fin.db.sqlite

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fin.db.sqlite.lrz
          asset_name: fin.db.sqlite.lrz
          tag: integration_test
          overwrite: true
          body: "Updated fin.db.sqlite.lrz"

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "adagrad"
          password: ${{ secrets.GHCR }}
          repository: adagrad/finget
          tags: integration_test
