name: "TEST yfinance all"

on:
  workflow_dispatch:

env:
  RUNTIME: 2

jobs:
  search_symbols:
    runs-on: ubuntu-latest
    name: A job to look for new symbols
    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Download database from release
        uses: robinraju/release-downloader@v1.4
        with:
          tag: integration_test
          fileName: "fin.db.sqlite.lrz.*"

      - name: Extract database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          ls -l
          cat fin.db.sqlite.lrz.?? > fin.db.sqlite.lrz
          rm fin.db.sqlite.lrz.??
          lrzip -f -d fin.db.sqlite.lrz -o fin.db.sqlite
          rm fin.db.sqlite.lrz

      - name: lookup new symbols
        uses: adagrad/findb_dolthub@integration_test
        with:
          args: "yfinance symbol --time ${{ env.RUNTIME }}"
          # resume last session
          # args: "yfinance symbol --time ${{ env.RUNTIME }}" -s yfsymbols.csv.existing.symbols -r yfsymbols.csv.possible.symbols

      - name: Archive database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip sqlite3
          sqlite3 fin.db.sqlite "begin; create table force_journal_cleanup (id integer primary key); rollback;"
          ls -l
          lrzip --lzo -f -o fin.db.sqlite.lrz fin.db.sqlite
          split -b50M fin.db.sqlite.lrz fin.db.sqlite.lrz.
          ls -l

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fin.db.sqlite.lrz.*
          tag: integration_test
          file_glob: true
          overwrite: true
          body: "Updated fin.db.sqlite.lrz"

  update_info:
    needs: search_symbols
    runs-on: ubuntu-latest
    name: A job to look for detailed infos for new symbols
    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Download database from release
        uses: robinraju/release-downloader@v1.4
        with:
          tag: integration_test
          fileName: "fin.db.sqlite.lrz.*"

      - name: Extract database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          ls -l
          cat fin.db.sqlite.lrz.?? > fin.db.sqlite.lrz
          rm fin.db.sqlite.lrz.??
          lrzip -f -d fin.db.sqlite.lrz -o fin.db.sqlite
          rm fin.db.sqlite.lrz

      - name: lookup info details
        uses: adagrad/findb_dolthub@integration_test
        with:
          args: "yfinance info --time ${{ env.RUNTIME }}"

      - name: Archive database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip sqlite3
          sqlite3 fin.db.sqlite "begin; create table force_journal_cleanup (id integer primary key); rollback;"
          ls -l
          lrzip --lzo -f -o fin.db.sqlite.lrz fin.db.sqlite
          split -b50M fin.db.sqlite.lrz fin.db.sqlite.lrz.
          ls -l

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fin.db.sqlite.lrz.*
          tag: integration_test
          file_glob: true
          overwrite: true
          body: "Updated fin.db.sqlite.lrz"

  update_quote:
    needs: update_info
    runs-on: ubuntu-latest
    name: A job to update missing quotes
    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: Download database from release
        uses: robinraju/release-downloader@v1.4
        with:
          tag: integration_test
          fileName: "fin.db.sqlite.lrz.*"

      - name: Extract database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          ls -l
          cat fin.db.sqlite.lrz.?? > fin.db.sqlite.lrz
          rm fin.db.sqlite.lrz.??
          lrzip -f -d fin.db.sqlite.lrz -o fin.db.sqlite
          rm fin.db.sqlite.lrz

      - name: fetch new quotes
        uses: adagrad/findb_dolthub@integration_test
        with:
          args: "yfinance quote -i 0 --include-new --time ${{ env.RUNTIME }} --clean"

      - name: Archive database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip sqlite3
          sqlite3 fin.db.sqlite "begin; create table force_journal_cleanup (id integer primary key); rollback;"
          ls -l
          lrzip --lzo -f -o fin.db.sqlite.lrz fin.db.sqlite
          split -b50M fin.db.sqlite.lrz fin.db.sqlite.lrz.
          ls -l

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fin.db.sqlite.lrz.*
          tag: integration_test
          file_glob: true
          overwrite: true
          body: "Updated fin.db.sqlite.lrz"
