name: Just Some Action Used for Testing

on:
  workflow_dispatch:

env:
  REPO: adagrad
  DATABASE: integration_test
  DOLTHUB_SECRET_JWT: ${{ secrets.DOLTHUB_SECRET_JWT }}
  DOLTHUB_SECRET: ${{ secrets.DOLTHUB_SECRET }}
  DOLT_BRANCH: "foo/bar-${{ github.run_id }}-${{ github.run_attempt }}"
  TEST_TABLE: "test"

jobs:
  test_job:
    runs-on: ubuntu-latest
    name: Test workflow
    steps:
      - name: count entries of table test
        id: count
        uses: adagrad/findb_dolthub@test
        with:
          args: "dolt sqlserver -d ${{ env.REPO }}/${{ env.DATABASE }} -b main --force-clone --and-exec \"dolt sql -q \\\"select count(*) from ${{ env.TEST_TABLE }};\\\"\""

      - name: dolt database status
        id: status
        uses: adagrad/findb_dolthub@test
        with:
          args: "dolt status"
