name: "TEST Upload Release Asset"

on:
  workflow_dispatch:


jobs:
  upload_asset:
    runs-on: ubuntu-latest
    name: Test uploading a release asset
    steps:

      - name: simulate database
        run: |
          touch fin.db.sqlite.lrz

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fin.db.sqlite.lrz
          asset_name: fin.db.sqlite.lrz
          tag: integration_test
          overwrite: true
          body: "Updated fin.db.sqlite.lrz"
