name: "Find New Symbols"

on:
  workflow_dispatch:
  schedule:
    # run once a week
    - cron: "0 1 * * 3"

jobs:
  search_symbols:
    runs-on: ubuntu-latest
    name: A job to look for new symbols
    outputs:
      branch: ${{ steps.symbols.outputs.branch }}
    steps:
      - name: lookup new symbols
        id: symbols
        uses: adagrad/findb_dolthub@v1
        env:
          REPO: adagrad
          DATABASE: findb
          DOLTHUB_SECRET_JWT: ${{ secrets.DOLTHUB_SECRET_JWT }}
          DOLTHUB_SECRET: ${{ secrets.DOLTHUB_SECRET }}
          DOLT_COMMIT_ARGS: "-m add_symbols"
        with:
          command1: yfinance
          command2: symbol
          command_args: "--time 300 --dolt-load"

  simulate_pr_merge:
    uses: adagrad/findb_dolthub/.github/workflows/local_merge.yml@main
    needs: search_symbols
    with:
      branch: ${{ needs.search_symbols.outputs.branch }}
