name: "Find New Symbols"

on:
  workflow_dispatch:
  schedule:
    # run once a week
    - cron: "0 12 * * 3"

env:
  REPO: adagrad
  DATABASE: findb
  DOLTHUB_SECRET_JWT: ${{ secrets.DOLTHUB_SECRET_JWT }}
  DOLTHUB_SECRET: ${{ secrets.DOLTHUB_SECRET }}
  DOLT_COMMIT_ARGS: "-m add_new_symbols --allow-empty"

jobs:
  search_symbols:
    runs-on: ubuntu-latest
    name: A job to look for new symbols
    outputs:
      branch: ${{ steps.search_symbols.outputs.branch }}
    steps:
      - name: lookup new symbols
        id: search_symbols
        uses: adagrad/findb_dolthub@v1
        with:
          command1: yfinance
          command2: symbol
          command_args: "--time 300 --dolt-load"

  simulate_pr_merge_symbol:
    uses: adagrad/findb_dolthub/.github/workflows/local_merge.yml@main
    needs: search_symbols
    secrets: inherit
    with:
      branch: ${{ needs.search_symbols.outputs.branch }}
      commit_message: add_symbols

  load_info:
    runs-on: ubuntu-latest
    needs: simulate_pr_merge_symbol
    name: A job to load the info of newly added symbols
    outputs:
      branch: ${{ steps.load_info.outputs.branch }}
    steps:
      - name: lookup new symbols
        id: load_info
        uses: adagrad/findb_dolthub@v1
        with:
          command1: yfinance
          command2: info
          command_args: "--time 300 --dolt-load"

  simulate_pr_merge_info:
    uses: adagrad/findb_dolthub/.github/workflows/local_merge.yml@main
    needs: load_info
    secrets: inherit
    with:
      branch: ${{ needs.load_info.outputs.branch }}
      commit_message: add_symbols_info
