name: "Find New Symbols"

on:
  workflow_dispatch:
  schedule:
    # run every other day
    - cron: "0 12 */2 * *"

env:
  RUNTIME: 5

jobs:
  search_symbols:
    runs-on: ubuntu-latest
    name: A job to look for new symbols
    steps:

      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: lookup new symbols
        uses: adagrad/findb_dolthub@latest
        with:
          args: "yfinance symbol --time ${{ env.RUNTIME }}"

      - name: 'Build:dockerimage'
        uses: docker/build-push-action@v1
        with:
          registry: ghcr.io
          username: "adagrad"
          password: ${{ secrets.GHCR }}
          repository: adagrad/findb_dolthub
          tags: latest

#  update_info:
#    needs: search_symbols
#    runs-on: ubuntu-latest
#    name: A job to look for detailed infos for new symbols
#    steps:
#      - name: lookup info details
#        uses: adagrad/findb_dolthub@latest
#        with:
#          args: "yfinance info --time ${{ env.RUNTIME }}"
#
#      - name: 'Build:dockerimage'
#        uses: docker/build-push-action@v1
#        with:
#          registry: ghcr.io
#          username: "adagrad"
#          password: ${{ secrets.PAT }}
#          repository: adagrad/findb_dolthub
#          tags: latest
