name: "Find New Symbols"

on:
  workflow_dispatch:
  #schedule:
  #  # run every other day
  #  - cron: "0 12 */2 * *"

env:
  REPO: adagrad
  DATABASE: findb
  DOLTHUB_SECRET_JWT: ${{ secrets.DOLTHUB_SECRET_JWT }}
  DOLTHUB_SECRET: ${{ secrets.DOLTHUB_SECRET }}
  DOLT_BRANCH_SYMBOL: "yfinance/symbol/${{ github.run_id }}-${{ github.run_attempt }}"
  DOLT_BRANCH_INFO: "yfinance/info/${{ github.run_id }}-${{ github.run_attempt }}"
  DOLT_COMMIT_MESSAGE: "add new symbols"

jobs:
  search_symbols:
    runs-on: ubuntu-latest
    name: A job to look for new symbols
    steps:
      - name: lookup new symbols
        id: search_symbols
        uses: adagrad/findb_dolthub@latest
        with:
          entrypoint: /entrypoint2.sh
          args: "dolt sqlserver -d ${{ env.REPO }}/${{ env.DATABASE }} -b main -f ${{ env.DOLT_BRANCH_SYMBOL }} --force-clone --and-exec \"fin-get yfinance symbol -d 'mysql+pymysql://root:@localhost/findb/main' --time 300 --dolt-load\""

      - name: push new symbols
        id: push_symbols
        uses: adagrad/findb_dolthub@latest
        with:
          entrypoint: /entrypoint2.sh
          args: "dolt push -a -m '${{ env.DDOLT_COMMIT_MESSAGE }}'"

  simulate_pr_merge_symbol:
    needs: search_symbols
    runs-on: ubuntu-latest
    name: Merge remote branch into main
    steps:
      - name: merge into main
        uses: adagrad/findb_dolthub@latest
        with:
          entrypoint: /entrypoint2.sh
          args: "dolt merge -d ${{ env.REPO }}/${{ env.DATABASE }} -s ${{ env.DOLT_BRANCH_SYMBOL }} -t main -m '${{ env.DDOLT_COMMIT_MESSAGE }}' --theirs -p"
