name: "Find New Symbols"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 12 * * *"

env:
  RUNTIME: 240

jobs:
  search_symbols:
    runs-on: ubuntu-latest
    name: A job to look for new symbols
    steps:

      - name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          root-reserve-mb: 512
          swap-size-mb: 1024
          remove-dotnet: 'true'

      - name: "Build:checkout"
        uses: actions/checkout@v2

      - name: Download database from release
        uses: robinraju/release-downloader@v1.4
        with:
          tag: latest
          fileName: "fin.db.sqlite.lrz.*"

      - name: Extract database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          ls -l
          cat fin.db.sqlite.lrz.?? > fin.db.sqlite.lrz
          rm fin.db.sqlite.lrz.??
          lrzip -f -d fin.db.sqlite.lrz -o fin.db.sqlite
          rm fin.db.sqlite.lrz

      - name: lookup new symbols
        uses: adagrad/findb_dolthub@latest
        with:
          args: "yfinance symbol --time ${{ env.RUNTIME }}"
          # resume last session
          # args: "yfinance symbol --time ${{ env.RUNTIME }}" -s yfsymbols.csv.existing.symbols -r yfsymbols.csv.possible.symbols

      - name: Archive database
        run: |
          sudo apt-get update
          sudo apt-get install lrzip
          lrzip --lzo -f -o fin.db.sqlite.lrz fin.db.sqlite
          split -b1900M fin.db.sqlite.lrz fin.db.sqlite.lrz.
          ls -l

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: fin.db.sqlite.lrz.*
          tag: latest
          file_glob: true
          overwrite: true
          body: "Updated fin.db.sqlite.lrz"