name: "Get new ENX quotes"

on:
  workflow_dispatch:
  schedule:
    # run once a week
    - cron: "0 1 * * 1"

env:
  REPO: adagrad
  DATABASE: findb
  DOLTHUB_SECRET_JWT: ${{ secrets.DOLTHUB_SECRET_JWT }}
  DOLTHUB_SECRET: ${{ secrets.DOLTHUB_SECRET }}
  DOLT_COMMIT_ARGS: "-m add_quotes --allow-empty"

jobs:
  fetch_quotes:
    runs-on: ubuntu-latest
    name: A job to look for new quotes
    outputs:
      branch: ${{ steps.quotes.outputs.branch }}
    steps:
      - name: lookup new symbols
        id: quotes
        uses: adagrad/findb_dolthub@v1
        with:
          command1: yfinance
          command2: quote
          command_args: "-w exchange='ENX' --time 300 --dolt-load"

  simulate_pr_merge:
    uses: adagrad/findb_dolthub/.github/workflows/local_merge.yml@main
    needs: fetch_quotes
    secrets: inherit
    with:
      branch: ${{ needs.fetch_quotes.outputs.branch }}
