name: "Get new TSI quotes (testable)"

on:
  workflow_dispatch:
  #schedule:
  #  # run once a week
  #  - cron: "0 6 * * 2"

env:
  DOLT_BRANCH: "yfinace/quote/tsi/${{ github.run_id }}-${{ github.run_attempt }}"

jobs:
  fetch_quotes:
    runs-on: ubuntu-latest
    name: A job to look for new quotes
    outputs:
      branch: ${{ steps.quotes.outputs.branch }}
    steps:
      - name: lookup TSI quotes
        id: quotes
        uses: adagrad/findb_dolthub@v1
        with:
          command1: yfinance
          command2: quote
          command_args: "-w exchange='TSI' --time 300 --dolt-load --clean"

  tsi_quotes:
    uses: adagrad/findb_dolthub/.github/workflows/local_merge.yml@main
    needs: fetch_quotes
    secrets: inherit
    with:
      branch: ${{ env.DOLT_BRANCH }}
      where: "exchange='PNK'"
      time: 15
      commit_message: add_quotes_tsi
