name: "Find new Symbols"

on:
  workflow_dispatch:
  schedule:
    # run once a month
    - cron: "0 1 1 * *"

jobs:
  hello_world_job:
    runs-on: ubuntu-latest
    name: A job to look for new symbols
    steps:
      - name: lookup new symbols
        uses: adagrad/findb_dolthub@v1
        env:
          REPO: adagrad
          DATABASE: findb
          DOLTHUB_SECRET: ${{ secrets.DOLTHUB_SECRET }}
        with:
          command1: yfinance
          command2: symbol
          command-args: --time 15 --dolt-load
