name: "Get new TSI quotes (testable)"

on:
  workflow_dispatch:
  #schedule:
  #  # run once a week
  #  - cron: "0 6 * * 2"

env:
  DOLT_BRANCH: "yfinance/quote/tsi/${{ github.run_id }}-${{ github.run_attempt }}"

jobs:
  tsi_quotes:
    uses: adagrad/findb_dolthub/.github/workflows/yfinance_quote_generic.yml@latest
    secrets: inherit
    with:
      branch: "yfinance/quote/tsi/${{ github.run_id }}-${{ github.run_attempt }}"
      where: "exchange='TSI'"
      time: 15
      commit_message: add_quotes_tsi
